[project]
name = "bot-hosting-wrapper_vortexsys"
version = "0.0.1"
authors = [
  { name="Vortex", email="vrtx.supp0rt@gmail.com" },
]
description = "An simple API Wrapper for bot-hosting.net"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
homepage = "https://github.com/vortexsys/bot-hosting-wrapper"
license = "MIT"
keywords = ["api wrapper", "bot-hosting.net"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"