[project]
name = "bot_hosting_wrapper_vortexsys"
version = "0.0.2"
authors = [
  { name="Vortex", email="vrtx.supp0rt@gmail.com" },
]
description = "An simple API Wrapper for bot-hosting.net"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
homepage = "https://github.com/vortexsys/bot-hosting-wrapper"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"